-- Modelo físico del Sistema de Gestión Académica FIIS–UNFV.
-- El semestre se almacena en curso.semestre; no existe plan_semestre.

CREATE TABLE facultad (
    cod_fac INTEGER PRIMARY KEY,
    den_fac VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE escuela (
    cod_fac INTEGER NOT NULL REFERENCES facultad(cod_fac),
    cod_esc INTEGER NOT NULL,
    den_escuela VARCHAR(120) NOT NULL,
    CONSTRAINT pk_escuela PRIMARY KEY (cod_fac, cod_esc),
    CONSTRAINT uq_escuela_nombre_facultad UNIQUE (cod_fac, den_escuela)
);

CREATE TABLE docente (
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    cod_docente VARCHAR(12) NOT NULL,
    apellidos_nombres VARCHAR(160) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    dedicacion VARCHAR(30) NOT NULL,
    departamento VARCHAR(100) NOT NULL,
    fuente VARCHAR(120) NOT NULL,
    CONSTRAINT pk_docente PRIMARY KEY (cod_fac, cod_esc, cod_docente),
    CONSTRAINT fk_docente_escuela FOREIGN KEY (cod_fac, cod_esc)
        REFERENCES escuela(cod_fac, cod_esc),
    CONSTRAINT uq_docente_nombre_escuela UNIQUE (cod_fac, cod_esc, apellidos_nombres)
);

CREATE TABLE plan_estudio (
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    den_plan VARCHAR(120) NOT NULL,
    anio_plan INTEGER NOT NULL,
    fecha_vigencia DATE NOT NULL,
    fecha_baja DATE,
    vigente BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_plan_estudio PRIMARY KEY (cod_fac, cod_esc, corr_pe),
    CONSTRAINT fk_plan_escuela FOREIGN KEY (cod_fac, cod_esc)
        REFERENCES escuela(cod_fac, cod_esc),
    CONSTRAINT uq_plan_anio_escuela UNIQUE (cod_fac, cod_esc, anio_plan),
    CONSTRAINT ck_plan_anio CHECK (anio_plan BETWEEN 1900 AND 2100),
    CONSTRAINT ck_plan_fechas CHECK (fecha_baja IS NULL OR fecha_baja >= fecha_vigencia)
);

CREATE TABLE curso (
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    cod_curso VARCHAR(20) NOT NULL,
    den_curso VARCHAR(160) NOT NULL,
    semestre INTEGER NOT NULL,
    ht INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 0,
    cred INTEGER NOT NULL,
    tipo_curso VARCHAR(20) NOT NULL DEFAULT 'OBLIGATORIO',
    CONSTRAINT pk_curso PRIMARY KEY (cod_fac, cod_esc, corr_pe, cod_curso),
    CONSTRAINT fk_curso_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe),
    CONSTRAINT ck_curso_semestre CHECK (semestre BETWEEN 1 AND 10),
    CONSTRAINT ck_curso_horas CHECK (ht >= 0 AND hp >= 0),
    CONSTRAINT ck_curso_creditos CHECK (cred > 0),
    CONSTRAINT ck_curso_tipo CHECK (tipo_curso IN ('OBLIGATORIO', 'ELECTIVO'))
);

CREATE TABLE curso_prerequisito (
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    cod_curso VARCHAR(20) NOT NULL,
    cod_curso_prerequisito VARCHAR(20) NOT NULL,
    CONSTRAINT pk_curso_prerequisito PRIMARY KEY
        (cod_fac, cod_esc, corr_pe, cod_curso, cod_curso_prerequisito),
    CONSTRAINT fk_prerequisito_curso FOREIGN KEY
        (cod_fac, cod_esc, corr_pe, cod_curso)
        REFERENCES curso(cod_fac, cod_esc, corr_pe, cod_curso) ON DELETE CASCADE,
    CONSTRAINT fk_prerequisito_requerido FOREIGN KEY
        (cod_fac, cod_esc, corr_pe, cod_curso_prerequisito)
        REFERENCES curso(cod_fac, cod_esc, corr_pe, cod_curso) ON DELETE RESTRICT,
    CONSTRAINT ck_prerequisito_distinto CHECK (cod_curso <> cod_curso_prerequisito)
);

CREATE TABLE periodo_academico (
    cod_periodo VARCHAR(10) PRIMARY KEY,
    den_periodo VARCHAR(80) NOT NULL UNIQUE,
    anio INTEGER NOT NULL,
    tipo_periodo VARCHAR(10) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_periodo_fechas CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT ck_periodo_anio CHECK (anio BETWEEN 2000 AND 2100),
    CONSTRAINT ck_periodo_tipo CHECK (tipo_periodo IN ('I','II','VERANO'))
);

CREATE TABLE periodo_matricula_acceso (
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo) ON DELETE CASCADE,
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    ciclo INTEGER NOT NULL,
    fase VARCHAR(10) NOT NULL DEFAULT 'CERRADA',
    CONSTRAINT pk_periodo_matricula_acceso PRIMARY KEY
        (cod_periodo, cod_fac, cod_esc, corr_pe, ciclo),
    CONSTRAINT fk_acceso_matricula_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe) ON DELETE CASCADE,
    CONSTRAINT ck_acceso_matricula_ciclo CHECK (ciclo BETWEEN 1 AND 10),
    CONSTRAINT ck_acceso_matricula_fase CHECK (fase IN ('CERRADA','TERCIO','TODOS'))
);

CREATE TABLE horario_cabecera (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo),
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    fecha_creacion DATE NOT NULL,
    CONSTRAINT fk_horario_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe),
    CONSTRAINT uq_horario_id_plan UNIQUE (id_horario, cod_fac, cod_esc, corr_pe),
    CONSTRAINT uq_horario_periodo_plan UNIQUE (cod_periodo, cod_fac, cod_esc, corr_pe)
);

CREATE TABLE horario_detalle (
    id_horario INTEGER NOT NULL REFERENCES horario_cabecera(id_horario) ON DELETE CASCADE,
    semestre_corr INTEGER NOT NULL,
    semestre_desc VARCHAR(30) NOT NULL,
    CONSTRAINT pk_horario_detalle PRIMARY KEY (id_horario, semestre_corr),
    CONSTRAINT ck_horario_semestre CHECK (semestre_corr BETWEEN 1 AND 10)
);

CREATE TABLE horario_curso (
    id_horario INTEGER NOT NULL,
    semestre_corr INTEGER NOT NULL,
    cod_curso VARCHAR(20) NOT NULL,
    cod_seccion VARCHAR(10) NOT NULL,
    tipo_sesion VARCHAR(1) NOT NULL,
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    dia_semana VARCHAR(10) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    aula VARCHAR(30) NOT NULL,
    CONSTRAINT pk_horario_curso PRIMARY KEY
        (id_horario, semestre_corr, cod_curso, cod_seccion, tipo_sesion, dia_semana, hora_inicio),
    CONSTRAINT fk_horario_curso_detalle FOREIGN KEY (id_horario, semestre_corr)
        REFERENCES horario_detalle(id_horario, semestre_corr) ON DELETE CASCADE,
    CONSTRAINT fk_horario_curso_plan_cabecera FOREIGN KEY
        (id_horario, cod_fac, cod_esc, corr_pe)
        REFERENCES horario_cabecera(id_horario, cod_fac, cod_esc, corr_pe) ON DELETE CASCADE,
    CONSTRAINT fk_horario_curso_malla FOREIGN KEY
        (cod_fac, cod_esc, corr_pe, cod_curso)
        REFERENCES curso(cod_fac, cod_esc, corr_pe, cod_curso),
    CONSTRAINT ck_horario_tipo_sesion CHECK (tipo_sesion IN ('T', 'P')),
    CONSTRAINT ck_horario_dia CHECK
        (dia_semana IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO')),
    CONSTRAINT ck_horario_horas CHECK (hora_fin > hora_inicio)
);

CREATE TABLE estudiante (
    cod_estudiante VARCHAR(10) PRIMARY KEY,
    dni VARCHAR(8) NOT NULL UNIQUE,
    apellidos_nombres VARCHAR(160) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    ciclo_actual INTEGER NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT fk_estudiante_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe),
    CONSTRAINT ck_estudiante_ciclo CHECK (ciclo_actual BETWEEN 1 AND 10),
    CONSTRAINT ck_estudiante_estado CHECK (estado IN ('ACTIVO','EGRESADO','RETIRADO')),
    CONSTRAINT ck_estudiante_codigo CHECK (cod_estudiante ~ '^[0-9]{10}$')
);

CREATE TABLE oferta_curso (
    id_oferta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo),
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    cod_curso VARCHAR(20) NOT NULL,
    cod_seccion VARCHAR(10) NOT NULL DEFAULT 'A',
    vacantes INTEGER NOT NULL DEFAULT 30,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    cod_docente VARCHAR(12),
    CONSTRAINT fk_oferta_curso FOREIGN KEY (cod_fac, cod_esc, corr_pe, cod_curso)
        REFERENCES curso(cod_fac, cod_esc, corr_pe, cod_curso),
    CONSTRAINT fk_oferta_docente FOREIGN KEY (cod_fac, cod_esc, cod_docente)
        REFERENCES docente(cod_fac, cod_esc, cod_docente),
    CONSTRAINT uq_oferta_periodo_curso_seccion UNIQUE
        (cod_periodo, cod_fac, cod_esc, corr_pe, cod_curso, cod_seccion),
    CONSTRAINT ck_oferta_vacantes CHECK (vacantes > 0)
);

CREATE TABLE prematricula (
    id_prematricula INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_estudiante VARCHAR(10) NOT NULL UNIQUE
        REFERENCES estudiante(cod_estudiante) ON DELETE CASCADE,
    cod_periodo VARCHAR(10) NOT NULL
        REFERENCES periodo_academico(cod_periodo) ON DELETE CASCADE
);

CREATE TABLE prematricula_detalle (
    id_prematricula INTEGER NOT NULL
        REFERENCES prematricula(id_prematricula) ON DELETE CASCADE,
    id_oferta INTEGER NOT NULL
        REFERENCES oferta_curso(id_oferta) ON DELETE CASCADE,
    CONSTRAINT pk_prematricula_detalle PRIMARY KEY (id_prematricula, id_oferta)
);

CREATE TABLE matricula (
    id_matricula INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_estudiante VARCHAR(10) NOT NULL REFERENCES estudiante(cod_estudiante),
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo),
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    ciclo_matricula INTEGER NOT NULL,
    fecha_matricula DATE NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'REGISTRADA',
    CONSTRAINT fk_matricula_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe),
    CONSTRAINT uq_matricula_estudiante_periodo UNIQUE (cod_estudiante, cod_periodo),
    CONSTRAINT ck_matricula_ciclo CHECK (ciclo_matricula BETWEEN 1 AND 10),
    CONSTRAINT ck_matricula_estado CHECK (estado IN ('REGISTRADA','ANULADA','CERRADA'))
);

CREATE TABLE matricula_detalle (
    id_matricula INTEGER NOT NULL REFERENCES matricula(id_matricula) ON DELETE CASCADE,
    id_oferta INTEGER NOT NULL REFERENCES oferta_curso(id_oferta),
    nota_practicas INTEGER,
    nota_parcial INTEGER,
    nota_examen_final INTEGER,
    nota_final INTEGER,
    resultado VARCHAR(12) NOT NULL DEFAULT 'MATRICULADO',
    CONSTRAINT pk_matricula_detalle PRIMARY KEY (id_matricula, id_oferta),
    CONSTRAINT ck_detalle_nota_practicas CHECK (nota_practicas IS NULL OR nota_practicas BETWEEN 0 AND 20),
    CONSTRAINT ck_detalle_nota_parcial CHECK (nota_parcial IS NULL OR nota_parcial BETWEEN 0 AND 20),
    CONSTRAINT ck_detalle_nota_examen_final CHECK (nota_examen_final IS NULL OR nota_examen_final BETWEEN 0 AND 20),
    CONSTRAINT ck_detalle_nota CHECK (nota_final IS NULL OR nota_final BETWEEN 0 AND 20),
    CONSTRAINT ck_detalle_resultado CHECK
        (resultado IN ('MATRICULADO','APROBADO','DESAPROBADO','RETIRADO'))
);

CREATE TABLE constancia_matricula (
    id_matricula INTEGER PRIMARY KEY
        REFERENCES matricula(id_matricula) ON DELETE CASCADE,
    firma_estudiante TEXT NOT NULL,
    contenido_pdf BYTEA NOT NULL,
    nombre_archivo VARCHAR(180) NOT NULL,
    fecha_generacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permiso (
    codigo VARCHAR(40) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE perfil (
    id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE perfil_permiso (
    id_perfil INTEGER NOT NULL REFERENCES perfil(id_perfil) ON DELETE CASCADE,
    cod_permiso VARCHAR(40) NOT NULL REFERENCES permiso(codigo) ON DELETE RESTRICT,
    CONSTRAINT pk_perfil_permiso PRIMARY KEY (id_perfil, cod_permiso)
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(60) NOT NULL UNIQUE,
    clave_hash VARCHAR(255) NOT NULL,
    nombre_mostrar VARCHAR(160) NOT NULL,
    cod_estudiante VARCHAR(10) UNIQUE
        REFERENCES estudiante(cod_estudiante) ON DELETE SET NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuario_perfil (
    id_usuario INTEGER NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_perfil INTEGER NOT NULL REFERENCES perfil(id_perfil) ON DELETE RESTRICT,
    CONSTRAINT pk_usuario_perfil PRIMARY KEY (id_usuario, id_perfil)
);

INSERT INTO permiso (codigo, nombre) VALUES
    ('GESTION_CURRICULAR', 'Gestión curricular'),
    ('MANTENIMIENTO_ACADEMICO', 'Mantenimiento académico'),
    ('PLANA_DOCENTE', 'Plana docente'),
    ('GESTION_ESTUDIANTES', 'Gestión de estudiantes'),
    ('GESTION_USUARIOS', 'Gestión de usuarios'),
    ('GESTION_PERFILES', 'Gestión de perfiles'),
    ('GESTION_MATRICULAS', 'Gestión de matrículas'),
    ('MATRICULA_PROPIA', 'Matrícula propia');

INSERT INTO perfil (codigo, nombre) VALUES
    ('ADMINISTRADOR', 'Administrador'),
    ('ESTUDIANTE', 'Estudiante'),
    ('JEFE_DEPARTAMENTO', 'Jefe de departamento'),
    ('DIRECTOR_ESCUELA', 'Director de escuela'),
    ('ADMINISTRACION', 'Administración');

INSERT INTO perfil_permiso (id_perfil, cod_permiso)
SELECT p.id_perfil, permisos.cod_permiso
FROM perfil p
JOIN (VALUES
    ('ADMINISTRADOR','GESTION_CURRICULAR'), ('ADMINISTRADOR','MANTENIMIENTO_ACADEMICO'),
    ('ADMINISTRADOR','PLANA_DOCENTE'), ('ADMINISTRADOR','GESTION_ESTUDIANTES'),
    ('ADMINISTRADOR','GESTION_USUARIOS'), ('ADMINISTRADOR','GESTION_PERFILES'),
    ('ADMINISTRADOR','GESTION_MATRICULAS'), ('ESTUDIANTE','MATRICULA_PROPIA'),
    ('JEFE_DEPARTAMENTO','MANTENIMIENTO_ACADEMICO'), ('JEFE_DEPARTAMENTO','PLANA_DOCENTE'),
    ('DIRECTOR_ESCUELA','GESTION_CURRICULAR'), ('DIRECTOR_ESCUELA','PLANA_DOCENTE'),
    ('ADMINISTRACION','GESTION_ESTUDIANTES'), ('ADMINISTRACION','GESTION_USUARIOS'),
    ('ADMINISTRACION','GESTION_MATRICULAS')
) AS permisos(codigo_perfil, cod_permiso) ON permisos.codigo_perfil = p.codigo;

CREATE INDEX ix_curso_plan_semestre
    ON curso(cod_fac, cod_esc, corr_pe, semestre);
CREATE INDEX ix_prerequisito_requerido
    ON curso_prerequisito(cod_fac, cod_esc, corr_pe, cod_curso_prerequisito);
CREATE INDEX ix_horario_aula_cruce
    ON horario_curso(dia_semana, aula, hora_inicio, hora_fin);
CREATE INDEX ix_horario_seccion_cruce
    ON horario_curso(id_horario, semestre_corr, cod_seccion, dia_semana, hora_inicio, hora_fin);
CREATE INDEX ix_oferta_periodo_plan
    ON oferta_curso(cod_periodo, cod_fac, cod_esc, corr_pe);
CREATE INDEX ix_oferta_docente
    ON oferta_curso(cod_fac, cod_esc, cod_docente);
CREATE INDEX ix_prematricula_detalle_oferta
    ON prematricula_detalle(id_oferta);
CREATE INDEX ix_perfil_permiso_codigo
    ON perfil_permiso(cod_permiso);
CREATE INDEX ix_matricula_estudiante
    ON matricula(cod_estudiante, cod_periodo);
