-- Ampliación no destructiva del sistema: períodos, estudiantes, ofertas y matrículas.
-- Ejecutar una sola vez sobre una base creada con la versión anterior.

ALTER TABLE periodo_academico ADD COLUMN IF NOT EXISTS anio INTEGER;
ALTER TABLE periodo_academico ADD COLUMN IF NOT EXISTS tipo_periodo VARCHAR(10);

UPDATE periodo_academico
SET anio = CAST(SUBSTRING(cod_periodo FROM 1 FOR 4) AS INTEGER),
    tipo_periodo = CASE
        WHEN cod_periodo LIKE '%-I' THEN 'I'
        WHEN cod_periodo LIKE '%-II' THEN 'II'
        ELSE 'VERANO'
    END
WHERE anio IS NULL OR tipo_periodo IS NULL;

ALTER TABLE periodo_academico ALTER COLUMN anio SET NOT NULL;
ALTER TABLE periodo_academico ALTER COLUMN tipo_periodo SET NOT NULL;
ALTER TABLE periodo_academico ADD CONSTRAINT ck_periodo_anio CHECK (anio BETWEEN 2000 AND 2100);
ALTER TABLE periodo_academico ADD CONSTRAINT ck_periodo_tipo CHECK (tipo_periodo IN ('I','II','VERANO'));

INSERT INTO periodo_academico
    (cod_periodo, den_periodo, anio, tipo_periodo, fecha_inicio, fecha_fin, activo)
VALUES
    ('2024-I','Semestre académico 2024-I',2024,'I','2024-03-18','2024-07-20',FALSE),
    ('2024-II','Semestre académico 2024-II',2024,'II','2024-08-19','2024-12-21',FALSE),
    ('2025-V','Ciclo de verano 2025',2025,'VERANO','2025-01-06','2025-02-28',FALSE),
    ('2025-I','Semestre académico 2025-I',2025,'I','2025-03-17','2025-07-19',FALSE),
    ('2025-II','Semestre académico 2025-II',2025,'II','2025-08-18','2025-12-20',FALSE),
    ('2026-V','Ciclo de verano 2026',2026,'VERANO','2026-01-05','2026-02-28',FALSE),
    ('2026-I','Semestre académico 2026-I',2026,'I','2026-03-16','2026-07-18',FALSE)
ON CONFLICT (cod_periodo) DO NOTHING;

CREATE TABLE IF NOT EXISTS estudiante (
    cod_estudiante VARCHAR(12) PRIMARY KEY,
    dni VARCHAR(8) NOT NULL UNIQUE,
    apellidos_nombres VARCHAR(160) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    ciclo_actual INTEGER NOT NULL CHECK (ciclo_actual BETWEEN 1 AND 10),
    estado VARCHAR(12) NOT NULL DEFAULT 'ACTIVO'
        CHECK (estado IN ('ACTIVO','EGRESADO','RETIRADO')),
    CONSTRAINT fk_estudiante_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe)
);

CREATE TABLE IF NOT EXISTS oferta_curso (
    id_oferta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo),
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    cod_curso VARCHAR(20) NOT NULL,
    cod_seccion VARCHAR(10) NOT NULL DEFAULT 'A',
    vacantes INTEGER NOT NULL DEFAULT 35 CHECK (vacantes > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_oferta_curso FOREIGN KEY (cod_fac, cod_esc, corr_pe, cod_curso)
        REFERENCES curso(cod_fac, cod_esc, corr_pe, cod_curso),
    CONSTRAINT uq_oferta_periodo_curso_seccion UNIQUE
        (cod_periodo, cod_fac, cod_esc, corr_pe, cod_curso, cod_seccion)
);

CREATE TABLE IF NOT EXISTS matricula (
    id_matricula INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_estudiante VARCHAR(12) NOT NULL REFERENCES estudiante(cod_estudiante),
    cod_periodo VARCHAR(10) NOT NULL REFERENCES periodo_academico(cod_periodo),
    cod_fac INTEGER NOT NULL,
    cod_esc INTEGER NOT NULL,
    corr_pe INTEGER NOT NULL,
    ciclo_matricula INTEGER NOT NULL CHECK (ciclo_matricula BETWEEN 1 AND 10),
    fecha_matricula DATE NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'REGISTRADA'
        CHECK (estado IN ('REGISTRADA','ANULADA','CERRADA')),
    CONSTRAINT fk_matricula_plan FOREIGN KEY (cod_fac, cod_esc, corr_pe)
        REFERENCES plan_estudio(cod_fac, cod_esc, corr_pe),
    CONSTRAINT uq_matricula_estudiante_periodo UNIQUE (cod_estudiante, cod_periodo)
);

CREATE TABLE IF NOT EXISTS matricula_detalle (
    id_matricula INTEGER NOT NULL REFERENCES matricula(id_matricula) ON DELETE CASCADE,
    id_oferta INTEGER NOT NULL REFERENCES oferta_curso(id_oferta),
    nota_final INTEGER CHECK (nota_final IS NULL OR nota_final BETWEEN 0 AND 20),
    resultado VARCHAR(12) NOT NULL DEFAULT 'MATRICULADO'
        CHECK (resultado IN ('MATRICULADO','APROBADO','DESAPROBADO','RETIRADO')),
    PRIMARY KEY (id_matricula, id_oferta)
);

INSERT INTO oferta_curso
    (cod_periodo, cod_fac, cod_esc, corr_pe, cod_curso, cod_seccion, vacantes, activo)
SELECT p.cod_periodo, c.cod_fac, c.cod_esc, c.corr_pe, c.cod_curso, 'A', 35, TRUE
FROM periodo_academico p
CROSS JOIN curso c
WHERE (p.tipo_periodo = 'I' AND MOD(c.semestre, 2) = 1)
   OR (p.tipo_periodo = 'II' AND MOD(c.semestre, 2) = 0)
   OR (p.tipo_periodo = 'VERANO' AND c.cod_curso IN ('P19-24','P19-33','P19-39','P19-41'))
ON CONFLICT (cod_periodo, cod_fac, cod_esc, corr_pe, cod_curso, cod_seccion)
DO NOTHING;

CREATE INDEX IF NOT EXISTS ix_oferta_periodo_plan
    ON oferta_curso(cod_periodo, cod_fac, cod_esc, corr_pe);
CREATE INDEX IF NOT EXISTS ix_matricula_estudiante
    ON matricula(cod_estudiante, cod_periodo);
